name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liG4RzILDl0sfnlB"
GITHUB_OWNER = "jswsq"
GITHUB_REPO = "nav"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav-3tg.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://nav-3tg.pages.dev"

